version: '3.3'
services:
  flask:
    container_name: flask_api_sample
    build: .
    volumes:
      - .:/src
    ports:
      - "5004:5000"
    #tty: true
    command: flask run --host 0.0.0.0 --port 5000